steps:
  # 1. composer install
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - -c
      - |
        apt-get update
        apt-get install -y php php-cli unzip curl
        curl -sS https://getcomposer.org/installer | php
        ( cd structure && php ../composer.phar install )
        ( cp root_files/* root_dir/)
        ( cp root_files/.htaccess root_dir/)
        ( cd root_dir && php ../composer.phar install )

  # 2. テーマインストール
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', './structure/install_themes.sh']

  # 3. プラグインインストール
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', './structure/install_plugins.sh']

  # 4. ルートディレクトリへのファイルコピー等
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', './structure/update_root.sh']

  # 5. Dockerイメージビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zero-wp:$COMMIT_SHA', '.']
    dir: '.'

images:
  - 'gcr.io/$PROJECT_ID/zero-wp:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
